version: "3.9"
services:
  flask_app:
    container_name: flask_app
    build: .
    entrypoint: ./entrypoint.sh
    ports:
      - "5001:5000"
    environment:
      - DATABASE_URL=postgresql+psycopg://postgres:676dac07@db:5432/flask_zero_db
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 676dac07
      POSTGRES_DB: flask_zero_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}
