services:
  flask_app:
    container_name: flask_app
    build: .
    entrypoint: ./entrypoint.sh
    ports:
      - "5001:5000" # <porta_host>:<porta_conteiner>
    environment:
      - DATABASE_URL=${SQLALCHEMY_DATABASE_URI}
    depends_on:
      - db
    image: epfolletto/flask_zero-flask_app:v2
  db:
    container_name: db
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 676dac07
      POSTGRES_DB: flask_zero_db
    ports:
      - "5434:5432" # <porta_host>:<porta_conteiner>
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}
