"""set default role for existing users

Revision ID: f9c225163fdf
Revises: 9831d7a59ae3
Create Date: 2024-11-08 10:30:49.826717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9c225163fdf'
down_revision: Union[str, None] = '9831d7a59ae3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Atualiza os registros existentes para garantir que todos tenham um valor padrão
    op.execute("UPDATE users SET role = 'user' WHERE role IS NULL")

    # Agora altera a coluna para não permitir valores nulos
    op.alter_column('users', 'role', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
